<x-layouts.app title="Mata Pelajaran - Ocular">
    <x-ui.page eyebrow="Data master" title="Mata pelajaran" description="Kelola daftar mata pelajaran dan pemakaiannya.">
        <x-slot:actions><x-ui.link-button :href="route('admin.subjects.create')">Tambah mata pelajaran</x-ui.link-button></x-slot:actions>
        <x-ui.flash :message="session('success')" />
        @if ($errors->any())<x-ui.flash type="error" :message="$errors->first()" />@endif
        <x-ui.card padding="p-4" class="border border-ocular-teal/15"><form method="GET" class="flex items-center gap-2"><label for="subject-search" class="sr-only">Cari mata pelajaran</label><div class="relative flex-1"><span class="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-ocular-accent">⌕</span><input id="subject-search" name="q" value="{{ $search }}" placeholder="Cari nama atau kode..." class="min-h-12 w-full border border-slate-300 pl-10 pr-4 text-sm outline-none focus:border-ocular-teal focus:ring-2 focus:ring-ocular-teal/20"></div><x-ui.button variant="teal">Cari</x-ui.button>@if ($search !== '')<x-ui.link-button :href="route('admin.subjects.index')" variant="muted">Reset</x-ui.link-button>@endif</form></x-ui.card>
        <x-ui.card padding="p-0" class="overflow-hidden border border-slate-200"><div class="border-b border-slate-200 px-4 py-4 sm:px-5"><h2 class="text-sm font-black uppercase tracking-widest text-ocular-teal">Daftar mata pelajaran</h2><p class="mt-1 text-xs text-ocular-copy/60">{{ $subjects->total() }} mata pelajaran</p></div><div class="hidden overflow-x-auto md:block"><table class="w-full min-w-[650px] text-left text-sm"><thead class="bg-ocular-surface text-[10px] uppercase tracking-widest text-ocular-accent"><tr><th class="px-5 py-3">Nama</th><th class="px-5 py-3">Kode</th><th class="px-5 py-3">Guru</th><th class="px-5 py-3">Jadwal</th><th class="px-5 py-3">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($subjects as $subject)<tr class="hover:bg-ocular-surface/60"><td class="px-5 py-3 font-semibold text-ocular-teal">{{ $subject->name }}</td><td class="px-5 py-3 font-mono text-xs">{{ $subject->code ?? '-' }}</td><td class="px-5 py-3">{{ $subject->teachers_count }}</td><td class="px-5 py-3">{{ $subject->schedules_count }}</td><td class="px-5 py-3"><div class="flex gap-3"><a href="{{ route('admin.subjects.edit', $subject) }}" class="text-xs font-bold text-ocular-teal underline">Edit</a><form method="POST" action="{{ route('admin.subjects.destroy', $subject) }}">@csrf @method('DELETE')<button class="text-xs font-bold text-rose-600 underline" onclick="return confirm('Hapus mata pelajaran ini?')">Hapus</button></form></div></td></tr>@empty<tr><td colspan="5" class="px-5 py-12 text-center text-sm text-ocular-copy/60">Belum ada data mata pelajaran.</td></tr>@endforelse</tbody></table></div><div class="divide-y divide-slate-100 md:hidden">@forelse ($subjects as $subject)<article class="space-y-3 p-4"><div class="flex items-start justify-between"><h3 class="font-semibold text-ocular-teal">{{ $subject->name }}</h3><span class="font-mono text-xs text-ocular-accent">{{ $subject->code ?? '-' }}</span></div><div class="grid grid-cols-2 gap-3 border-t border-slate-100 pt-3 text-xs"><div><p class="text-ocular-copy/50">Guru</p><p class="mt-1 font-semibold">{{ $subject->teachers_count }}</p></div><div><p class="text-ocular-copy/50">Jadwal</p><p class="mt-1 font-semibold">{{ $subject->schedules_count }}</p></div></div><div class="flex gap-3 border-t border-slate-100 pt-3"><a href="{{ route('admin.subjects.edit', $subject) }}" class="text-xs font-bold text-ocular-teal underline">Edit</a><form method="POST" action="{{ route('admin.subjects.destroy', $subject) }}">@csrf @method('DELETE')<button class="text-xs font-bold text-rose-600 underline" onclick="return confirm('Hapus mata pelajaran ini?')">Hapus</button></form></div></article>@empty<p class="px-4 py-12 text-center text-sm text-ocular-copy/60">Belum ada data mata pelajaran.</p>@endforelse</div><div class="px-4 pb-4 sm:px-5"><x-ui.pagination :paginator="$subjects" /></div></x-ui.card>
    </x-ui.page>
</x-layouts.app>
