<x-layouts.app title="Mata Pelajaran - Ocular">
    <x-ui.page eyebrow="Data master" title="Mata pelajaran">
        <x-slot:actions><x-ui.link-button :href="route('admin.subjects.create')">Tambah mata pelajaran</x-ui.link-button></x-slot:actions>
        <x-ui.flash :message="session('success')" />
        @if (session('warning')) <x-ui.flash type="warning" :message="session('warning')" /> @endif
        @if ($errors->any()) <x-ui.flash type="error" :message="$errors->first()" /> @endif
        <x-ui.card padding="p-0" class="overflow-hidden border border-slate-200">
            <div class="flex flex-col gap-3 border-b border-slate-200 px-4 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-5"><div><h2 class="text-sm font-black uppercase tracking-widest text-ocular-teal">Daftar mata pelajaran</h2><p class="mt-1 text-xs text-ocular-copy/60">{{ $subjects->total() }} mata pelajaran</p></div><div class="flex flex-wrap items-center justify-end gap-2"><form method="GET" class="flex min-w-0 items-center gap-2 sm:w-[20rem]"><x-ui.search-input name="search" :value="$search" placeholder="Cari nama atau kode..." id="subject-search" /><x-ui.button variant="teal" class="min-h-10 px-3">Cari</x-ui.button>@if ($search !== '')<x-ui.link-button :href="route('admin.subjects.index')" variant="muted" class="min-h-10 px-3">Reset</x-ui.link-button>@endif</form><x-ui.bulk-actions form-id="bulk-subjects-form" :action="route('admin.subjects.bulk-destroy')" checkbox-name="subject_ids[]" confirm-message="Hapus semua mata pelajaran yang dipilih? Mapel yang masih dipakai guru atau jadwal akan dilewati." /></div></div>
            <div class="hidden overflow-x-auto md:block"><table class="w-full min-w-[700px] text-left text-sm"><thead class="bg-ocular-surface text-[10px] uppercase tracking-widest text-ocular-accent"><tr><th class="w-12 px-5 py-3">Pilih</th><th class="px-5 py-3">Nama</th><th class="px-5 py-3">Kode</th><th class="px-5 py-3">Guru</th><th class="px-5 py-3">Jadwal</th><th class="px-5 py-3">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">
                @forelse ($subjects as $subject)<tr class="hover:bg-ocular-surface/60"><td class="px-5 py-3"><input type="checkbox" name="subject_ids[]" value="{{ $subject->id }}" form="bulk-subjects-form" data-bulk-checkbox="bulk-subjects-form" data-bulk-id="{{ $subject->id }}" class="size-4 border-slate-300 text-ocular-teal"></td><td class="px-5 py-3 font-semibold text-ocular-teal">{{ $subject->name }}</td><td class="px-5 py-3 font-mono text-xs">{{ $subject->code ?? '-' }}</td><td class="px-5 py-3">{{ $subject->teachers_count }}</td><td class="px-5 py-3">{{ $subject->schedules_count }}</td><td class="px-5 py-3"><x-ui.row-actions :edit-href="route('admin.subjects.edit', $subject)" :delete-action="route('admin.subjects.destroy', $subject)" confirm="Hapus mata pelajaran ini?" /></td></tr>@empty<tr><td colspan="6" class="px-5 py-12 text-center text-sm text-ocular-copy/60">Belum ada data mata pelajaran.</td></tr>@endforelse
            </tbody></table></div>
            <div class="divide-y divide-slate-100 md:hidden">@forelse ($subjects as $subject)<article class="space-y-3 p-4"><div class="flex items-start gap-3"><input type="checkbox" name="subject_ids[]" value="{{ $subject->id }}" form="bulk-subjects-form" data-bulk-checkbox="bulk-subjects-form" data-bulk-id="{{ $subject->id }}" class="mt-1 size-4 border-slate-300 text-ocular-teal"><div class="flex w-full items-start justify-between"><h3 class="font-semibold text-ocular-teal">{{ $subject->name }}</h3><span class="font-mono text-xs text-ocular-accent">{{ $subject->code ?? '-' }}</span></div></div><div class="grid grid-cols-2 gap-3 border-t border-slate-100 pt-3 text-xs"><div><p class="text-ocular-copy/50">Guru</p><p class="mt-1 font-semibold">{{ $subject->teachers_count }}</p></div><div><p class="text-ocular-copy/50">Jadwal</p><p class="mt-1 font-semibold">{{ $subject->schedules_count }}</p></div></div><x-ui.row-actions class="border-t border-slate-100 pt-3" :edit-href="route('admin.subjects.edit', $subject)" :delete-action="route('admin.subjects.destroy', $subject)" confirm="Hapus mata pelajaran ini?" /></article>@empty<p class="px-4 py-12 text-center text-sm text-ocular-copy/60">Belum ada data mata pelajaran.</p>@endforelse</div>
            <div class="px-4 pb-4 sm:px-5"><x-ui.pagination :paginator="$subjects" /></div>
        </x-ui.card>
    </x-ui.page>
</x-layouts.app>
