<x-layouts.app title="Siswa - Ocular">
    <x-ui.page eyebrow="Data master" title="Siswa" description="Kelola data siswa, kelas, status aktif, dan import CSV.">
        <x-slot:actions><x-ui.link-button :href="route('admin.students.promotion')" variant="outline">Kenaikan kelas</x-ui.link-button><x-ui.link-button :href="route('admin.students.create')">Tambah siswa</x-ui.link-button></x-slot:actions>
        <x-ui.flash :message="session('success')" />
        @if (session('warning'))<x-ui.flash type="warning" :message="session('warning')" />@endif
        @if ($errors->any())<x-ui.flash type="error" :message="$errors->first()" />@endif
        <x-ui.card class="border border-dashed border-ocular-accent/40"><form method="POST" action="{{ route('admin.students.import') }}" enctype="multipart/form-data" class="flex flex-col gap-3 sm:flex-row sm:items-end"><div class="flex-1"><label for="student-csv" class="block text-xs font-bold uppercase tracking-wider text-ocular-teal">Import CSV</label><p class="mt-1 text-xs text-ocular-copy/60">Kolom: nis, nisn, name, class_id, is_active</p><input id="student-csv" type="file" name="file" accept=".csv,text/csv" required class="mt-2 min-h-11 w-full border border-slate-300 bg-white px-3 py-2 text-sm">@csrf</div><x-ui.button variant="teal">Import siswa</x-ui.button></form></x-ui.card>
        <x-ui.card padding="p-4" class="border border-ocular-teal/15"><form method="GET" class="grid items-end gap-3 sm:grid-cols-[1fr_16rem_auto_auto]"><label class="block text-xs font-bold uppercase tracking-wider text-ocular-teal">Cari siswa<input name="search" value="{{ $search }}" placeholder="Nama, NIS, atau NISN..." class="mt-2 min-h-11 w-full border border-slate-300 px-3 text-sm focus:border-ocular-teal focus:outline-none focus:ring-2 focus:ring-ocular-teal/20"></label><label class="block text-xs font-bold uppercase tracking-wider text-ocular-teal">Kelas<select name="class_id" class="mt-2 min-h-11 w-full border border-slate-300 bg-white px-3 text-sm"><option value="">Semua kelas</option>@foreach ($classes as $class)<option value="{{ $class->id }}" @selected($selectedClassId == $class->id)>{{ $class->name }} · {{ $class->academicYear->name }}</option>@endforeach</select></label><x-ui.button variant="teal">Cari</x-ui.button><x-ui.link-button :href="route('admin.students.index')" variant="muted">Reset</x-ui.link-button></form></x-ui.card>
        <x-ui.card padding="p-0" class="overflow-hidden border border-slate-200"><div class="border-b border-slate-200 px-4 py-4 sm:px-5"><h2 class="text-sm font-black uppercase tracking-widest text-ocular-teal">Daftar siswa</h2><p class="mt-1 text-xs text-ocular-copy/60">{{ $students->total() }} siswa</p></div><div class="hidden overflow-x-auto md:block"><table class="w-full min-w-[820px] text-left text-sm"><thead class="bg-ocular-surface text-[10px] uppercase tracking-widest text-ocular-accent"><tr><th class="px-5 py-3">Nama</th><th class="px-5 py-3">NIS</th><th class="px-5 py-3">NISN</th><th class="px-5 py-3">Kelas</th><th class="px-5 py-3">Status</th><th class="px-5 py-3">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($students as $student)<tr class="hover:bg-ocular-surface/60"><td class="px-5 py-3 font-semibold text-ocular-teal">{{ $student->name }}</td><td class="px-5 py-3 font-mono text-xs">{{ $student->nis }}</td><td class="px-5 py-3 font-mono text-xs">{{ $student->nisn }}</td><td class="px-5 py-3">{{ $student->schoolClass->name }}</td><td class="px-5 py-3"><x-ui.status-badge :status="$student->is_active ? 'open' : 'closed'" :label="$student->is_active ? 'Aktif' : 'Nonaktif'" /></td><td class="px-5 py-3"><div class="flex gap-3"><a href="{{ route('admin.students.edit', $student) }}" class="text-xs font-bold text-ocular-teal underline">Edit</a><form method="POST" action="{{ route('admin.students.destroy', $student) }}">@csrf @method('DELETE')<button class="text-xs font-bold text-rose-600 underline" onclick="return confirm('Hapus siswa ini?')">Hapus</button></form></div></td></tr>@empty<tr><td colspan="6" class="px-5 py-12 text-center text-sm text-ocular-copy/60">Belum ada data siswa.</td></tr>@endforelse</tbody></table></div><div class="divide-y divide-slate-100 md:hidden">@forelse ($students as $student)<article class="space-y-3 p-4"><div class="flex items-start justify-between gap-3"><div><h3 class="font-semibold text-ocular-teal">{{ $student->name }}</h3><p class="mt-1 font-mono text-[10px] text-ocular-copy/60">NIS {{ $student->nis }} · NISN {{ $student->nisn }}</p></div><x-ui.status-badge :status="$student->is_active ? 'open' : 'closed'" :label="$student->is_active ? 'Aktif' : 'Nonaktif'" /></div><p class="text-xs text-ocular-copy/70">Kelas {{ $student->schoolClass->name }}</p><div class="flex gap-3 border-t border-slate-100 pt-3"><a href="{{ route('admin.students.edit', $student) }}" class="text-xs font-bold text-ocular-teal underline">Edit</a><form method="POST" action="{{ route('admin.students.destroy', $student) }}">@csrf @method('DELETE')<button class="text-xs font-bold text-rose-600 underline" onclick="return confirm('Hapus siswa ini?')">Hapus</button></form></div></article>@empty<p class="px-4 py-12 text-center text-sm text-ocular-copy/60">Belum ada data siswa.</p>@endforelse</div><div class="px-4 pb-4 sm:px-5"><x-ui.pagination :paginator="$students" /></div></x-ui.card>
    </x-ui.page>
</x-layouts.app>
