<x-layouts.app title="Tahun Ajaran - Ocular">
    <x-ui.page eyebrow="Pengaturan akademik" title="Tahun ajaran" description="Atur periode akademik yang digunakan oleh kelas dan jadwal.">
        <x-slot:actions><x-ui.link-button :href="route('admin.academic-years.create')">Tambah tahun ajaran</x-ui.link-button></x-slot:actions>
        <x-ui.flash :message="session('success')" />
        @if (session('warning')) <x-ui.flash type="warning" :message="session('warning')" /> @endif
        @if ($errors->any()) <x-ui.flash type="error" :message="$errors->first()" /> @endif
        <x-ui.card padding="p-0" class="overflow-hidden border border-slate-200">
            <div class="flex flex-col gap-3 border-b border-slate-200 px-4 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-5"><div><h2 class="text-sm font-black uppercase tracking-widest text-ocular-teal">Periode akademik</h2><p class="mt-1 text-xs text-ocular-copy/60">{{ $academicYears->total() }} periode · pilih periode di halaman ini untuk aksi massal</p></div><div class="flex flex-wrap items-center justify-end gap-2"><form method="GET" class="flex min-w-0 items-center gap-2 sm:w-[20rem]"><x-ui.search-input name="search" :value="$search" placeholder="Cari tahun ajaran..." id="year-search" /><x-ui.button variant="teal" class="min-h-10 px-3">Cari</x-ui.button>@if ($search !== '')<x-ui.link-button :href="route('admin.academic-years.index')" variant="muted" class="min-h-10 px-3">Reset</x-ui.link-button>@endif</form><x-ui.bulk-actions form-id="bulk-academic-years-form" :action="route('admin.academic-years.bulk-destroy')" checkbox-name="academic_year_ids[]" confirm-message="Hapus semua tahun ajaran yang dipilih? Periode yang masih punya kelas atau jadwal akan dilewati." /></div></div>
            <div class="hidden overflow-x-auto md:block"><table class="w-full min-w-[760px] text-left text-sm"><thead class="bg-ocular-surface text-[10px] uppercase tracking-widest text-ocular-accent"><tr><th class="w-12 px-5 py-3">Pilih</th><th class="px-5 py-3">Nama</th><th class="px-5 py-3">Semester</th><th class="px-5 py-3">Periode</th><th class="px-5 py-3">Status</th><th class="px-5 py-3">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">
                @forelse ($academicYears as $academicYear)<tr class="hover:bg-ocular-surface/60"><td class="px-5 py-3"><input type="checkbox" name="academic_year_ids[]" value="{{ $academicYear->id }}" form="bulk-academic-years-form" data-bulk-checkbox="bulk-academic-years-form" data-bulk-id="{{ $academicYear->id }}" class="size-4 border-slate-300 text-ocular-teal"></td><td class="px-5 py-3 font-semibold text-ocular-teal">{{ $academicYear->name }}</td><td class="px-5 py-3">{{ $academicYear->semester === 1 ? 'Ganjil' : 'Genap' }}</td><td class="px-5 py-3 font-mono text-xs">{{ $academicYear->start_date->format('d/m/Y') }} – {{ $academicYear->end_date->format('d/m/Y') }}</td><td class="px-5 py-3"><x-ui.status-badge :status="$academicYear->is_active ? 'open' : 'closed'" :label="$academicYear->is_active ? 'Aktif' : 'Nonaktif'" /></td><td class="px-5 py-3"><x-ui.row-actions :edit-href="route('admin.academic-years.edit', $academicYear)" :delete-action="route('admin.academic-years.destroy', $academicYear)" confirm="Hapus tahun ajaran ini?" /></td></tr>@empty<tr><td colspan="6" class="px-5 py-12 text-center text-sm text-ocular-copy/60">Belum ada tahun ajaran.</td></tr>@endforelse
            </tbody></table></div>
            <div class="divide-y divide-slate-100 md:hidden">@forelse ($academicYears as $academicYear)<article class="space-y-3 p-4"><div class="flex items-start gap-3"><input type="checkbox" name="academic_year_ids[]" value="{{ $academicYear->id }}" form="bulk-academic-years-form" data-bulk-checkbox="bulk-academic-years-form" data-bulk-id="{{ $academicYear->id }}" class="mt-1 size-4 border-slate-300 text-ocular-teal"><div class="flex w-full items-start justify-between gap-3"><div><h3 class="font-semibold text-ocular-teal">{{ $academicYear->name }}</h3><p class="mt-1 text-xs text-ocular-copy/60">{{ $academicYear->semester === 1 ? 'Ganjil' : 'Genap' }}</p></div><x-ui.status-badge :status="$academicYear->is_active ? 'open' : 'closed'" :label="$academicYear->is_active ? 'Aktif' : 'Nonaktif'" /></div></div><p class="font-mono text-xs text-ocular-copy/70">{{ $academicYear->start_date->format('d/m/Y') }} – {{ $academicYear->end_date->format('d/m/Y') }}</p><x-ui.row-actions class="border-t border-slate-100 pt-3" :edit-href="route('admin.academic-years.edit', $academicYear)" :delete-action="route('admin.academic-years.destroy', $academicYear)" confirm="Hapus tahun ajaran ini?" /></article>@empty<p class="px-4 py-12 text-center text-sm text-ocular-copy/60">Belum ada tahun ajaran.</p>@endforelse</div>
            <div class="px-4 pb-4 sm:px-5"><x-ui.pagination :paginator="$academicYears" /></div>
        </x-ui.card>
    </x-ui.page>
</x-layouts.app>
