<x-layouts.app title="Kelas - Ocular">
    <x-ui.page eyebrow="Data master" title="Kelas" description="Kelola kelas berdasarkan tahun ajaran.">
        <x-slot:actions><x-ui.link-button :href="route('admin.classes.create')">Tambah kelas</x-ui.link-button></x-slot:actions>
        <x-ui.flash :message="session('success')" />
        @if (session('warning')) <x-ui.flash type="warning" :message="session('warning')" /> @endif
        @if ($errors->any()) <x-ui.flash type="error" :message="$errors->first()" /> @endif
        <x-ui.card padding="p-0" class="overflow-hidden border border-slate-200">
            <div class="flex flex-col gap-3 border-b border-slate-200 px-4 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-5"><div><h2 class="text-sm font-black uppercase tracking-widest text-ocular-teal">Daftar kelas</h2><p class="mt-1 text-xs text-ocular-copy/60">{{ $classes->total() }} kelas · pilih kelas di halaman ini untuk aksi massal</p></div><div class="flex flex-wrap items-center justify-end gap-2"><form method="GET" class="flex min-w-0 items-center gap-2 sm:w-[18rem]"><x-ui.search-input name="search" :value="$search" placeholder="Cari nama kelas..." id="class-search" /><x-ui.button variant="teal" class="min-h-10 px-3">Cari</x-ui.button>@if ($search !== '')<x-ui.link-button :href="route('admin.classes.index')" variant="muted" class="min-h-10 px-3">Reset</x-ui.link-button>@endif</form><x-ui.bulk-actions form-id="bulk-classes-form" :action="route('admin.classes.bulk-destroy')" checkbox-name="class_ids[]" confirm-message="Hapus semua kelas yang dipilih? Kelas yang masih punya siswa atau jadwal akan dilewati." /></div></div>
            <div class="hidden overflow-x-auto md:block"><table class="w-full min-w-[700px] text-left text-sm"><thead class="bg-ocular-surface text-[10px] uppercase tracking-widest text-ocular-accent"><tr><th class="w-12 px-5 py-3">Pilih</th><th class="px-5 py-3">Nama</th><th class="px-5 py-3">Tingkat</th><th class="px-5 py-3">Tahun ajaran</th><th class="px-5 py-3">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">
                @forelse ($classes as $class)<tr class="hover:bg-ocular-surface/60"><td class="px-5 py-3"><input type="checkbox" name="class_ids[]" value="{{ $class->id }}" form="bulk-classes-form" data-bulk-checkbox="bulk-classes-form" data-bulk-id="{{ $class->id }}" class="size-4 border-slate-300 text-ocular-teal"></td><td class="px-5 py-3 font-semibold text-ocular-teal">{{ $class->name }}</td><td class="px-5 py-3">{{ $class->grade_level }}</td><td class="px-5 py-3">{{ $class->academicYear->name }} · {{ $class->academicYear->semester === 1 ? 'Ganjil' : 'Genap' }}</td><td class="px-5 py-3"><x-ui.row-actions :edit-href="route('admin.classes.edit', $class)" :delete-action="route('admin.classes.destroy', $class)" confirm="Hapus kelas ini?" /></td></tr>@empty<tr><td colspan="5" class="px-5 py-12 text-center text-sm text-ocular-copy/60">Belum ada data kelas.</td></tr>@endforelse
            </tbody></table></div>
            <div class="divide-y divide-slate-100 md:hidden">@forelse ($classes as $class)<article class="space-y-3 p-4"><div class="flex items-start gap-3"><input type="checkbox" name="class_ids[]" value="{{ $class->id }}" form="bulk-classes-form" data-bulk-checkbox="bulk-classes-form" data-bulk-id="{{ $class->id }}" class="mt-1 size-4 border-slate-300 text-ocular-teal"><div class="flex w-full items-start justify-between"><h3 class="font-semibold text-ocular-teal">{{ $class->name }}</h3><span class="bg-ocular-teal/10 px-2 py-1 text-[10px] font-black text-ocular-teal">TINGKAT {{ $class->grade_level }}</span></div></div><p class="text-xs text-ocular-copy/70">{{ $class->academicYear->name }} · {{ $class->academicYear->semester === 1 ? 'Ganjil' : 'Genap' }}</p><x-ui.row-actions class="border-t border-slate-100 pt-3" :edit-href="route('admin.classes.edit', $class)" :delete-action="route('admin.classes.destroy', $class)" confirm="Hapus kelas ini?" /></article>@empty<p class="px-4 py-12 text-center text-sm text-ocular-copy/60">Belum ada data kelas.</p>@endforelse</div>
            <div class="px-4 pb-4 sm:px-5"><x-ui.pagination :paginator="$classes" /></div>
        </x-ui.card>
    </x-ui.page>
</x-layouts.app>
