<x-layouts.app title="Guru - Ocular">
    <x-ui.page eyebrow="Data master" title="Guru" description="Kelola akun guru dan mata pelajaran yang diampu.">
        <x-slot:actions><x-ui.link-button :href="route('admin.teachers.create')">Tambah guru</x-ui.link-button></x-slot:actions>
        <x-ui.flash :message="session('success')" />
        @if ($errors->any())<x-ui.flash type="error" :message="$errors->first()" />@endif
        <x-ui.card padding="p-4" class="border border-ocular-teal/15">
            <form method="GET" class="flex items-center gap-2"><label for="teacher-search" class="sr-only">Cari guru</label><div class="relative flex-1"><span class="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-ocular-accent">⌕</span><input id="teacher-search" name="q" value="{{ $search }}" placeholder="Cari nama, email, atau NIP..." class="min-h-12 w-full border border-slate-300 pl-10 pr-4 text-sm outline-none focus:border-ocular-teal focus:ring-2 focus:ring-ocular-teal/20"></div><x-ui.button variant="teal">Cari</x-ui.button>@if ($search !== '')<x-ui.link-button :href="route('admin.teachers.index')" variant="muted">Reset</x-ui.link-button>@endif</form>
        </x-ui.card>
        <x-ui.card padding="p-0" class="overflow-hidden border border-slate-200">
            <div class="flex items-center justify-between gap-3 border-b border-slate-200 px-4 py-4 sm:px-5"><div><h2 class="text-sm font-black uppercase tracking-widest text-ocular-teal">Daftar guru</h2><p class="mt-1 text-xs text-ocular-copy/60">{{ $teachers->total() }} akun</p></div></div>
            <div class="hidden overflow-x-auto md:block"><table class="w-full min-w-[850px] text-left text-sm"><thead class="bg-ocular-surface text-[10px] uppercase tracking-widest text-ocular-accent"><tr><th class="px-5 py-3">Nama</th><th class="px-5 py-3">Email</th><th class="px-5 py-3">NIP</th><th class="px-5 py-3">Mata pelajaran</th><th class="px-5 py-3">Status</th><th class="px-5 py-3">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">
                @forelse ($teachers as $teacher)<tr class="hover:bg-ocular-surface/60"><td class="px-5 py-3 font-semibold text-ocular-teal">{{ $teacher->name }}</td><td class="px-5 py-3">{{ $teacher->email }}</td><td class="px-5 py-3 font-mono text-xs">{{ $teacher->nip ?? '-' }}</td><td class="max-w-xs px-5 py-3 text-xs">{{ $teacher->subjects->pluck('name')->join(', ') ?: '-' }}</td><td class="px-5 py-3"><x-ui.status-badge :status="$teacher->is_active ? 'open' : 'closed'" :label="$teacher->is_active ? 'Aktif' : 'Nonaktif'" /></td><td class="px-5 py-3"><div class="flex gap-3"><a href="{{ route('admin.teachers.edit', $teacher) }}" class="text-xs font-bold text-ocular-teal underline">Edit</a><form method="POST" action="{{ route('admin.teachers.destroy', $teacher) }}">@csrf @method('DELETE')<button class="text-xs font-bold text-rose-600 underline" onclick="return confirm('Hapus guru ini?')">Hapus</button></form></div></td></tr>@empty<tr><td colspan="6" class="px-5 py-12 text-center text-sm text-ocular-copy/60">Belum ada data guru.</td></tr>@endforelse
            </tbody></table></div>
            <div class="divide-y divide-slate-100 md:hidden">@forelse ($teachers as $teacher)<article class="space-y-3 p-4"><div class="flex items-start justify-between gap-3"><div><h3 class="font-semibold text-ocular-teal">{{ $teacher->name }}</h3><p class="mt-1 text-xs text-ocular-copy/60">{{ $teacher->email }}</p></div><x-ui.status-badge :status="$teacher->is_active ? 'open' : 'closed'" :label="$teacher->is_active ? 'Aktif' : 'Nonaktif'" /></div><dl class="grid grid-cols-2 gap-3 border-t border-slate-100 pt-3 text-xs"><div><dt class="text-ocular-copy/50">NIP</dt><dd class="mt-1 font-mono">{{ $teacher->nip ?? '-' }}</dd></div><div><dt class="text-ocular-copy/50">Mapel</dt><dd class="mt-1">{{ $teacher->subjects->pluck('name')->join(', ') ?: '-' }}</dd></div></dl><div class="flex gap-3 border-t border-slate-100 pt-3"><a href="{{ route('admin.teachers.edit', $teacher) }}" class="text-xs font-bold text-ocular-teal underline">Edit</a><form method="POST" action="{{ route('admin.teachers.destroy', $teacher) }}">@csrf @method('DELETE')<button class="text-xs font-bold text-rose-600 underline" onclick="return confirm('Hapus guru ini?')">Hapus</button></form></div></article>@empty<p class="px-4 py-12 text-center text-sm text-ocular-copy/60">Belum ada data guru.</p>@endforelse</div>
            <div class="px-4 pb-4 sm:px-5"><x-ui.pagination :paginator="$teachers" /></div>
        </x-ui.card>
    </x-ui.page>
</x-layouts.app>
